# fly.toml file generated for lively-water-7363 on 2023-01-28T13:19:18-06:00

app = "lively-water-7363"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  CHOKIDAR_USEPOLLING = "true"

[experimental]
  auto_rollback = true

[mounts]
  destination = "/"
  source = "brindows_app_data"

[[services]]
  http_checks = []
  internal_port = 80
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
